### ISSUE TITLE
Error for logging on __del__

### ISSUE THREAD

**Issue by SasCezar** [Lynten/stanford-corenlp#15]
I had the following error using the latest version: 
```
2017-11-06 08:36:46,679 root         INFO     Cleanup...
Exception ignored in: <bound method StanfordCoreNLP.__del__ of <stanfordcorenlp.corenlp.StanfordCoreNLP object at 0x0000021304456F98>>
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\stanfordcorenlp\corenlp.py", line 108, in __del__
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 1838, in info
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 1279, in info
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 1415, in _log
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 1425, in handle
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 1487, in callHandlers
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 855, in handle
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 1047, in emit
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 1037, in _open
NameError: name 'open' is not defined
```

According to this: https://bugs.python.org/issue26789 will be better to remove the logging from the __del__ method (in my case works). 
Note that i set the logger to save to file.

**Comment by Lynten** [comment]
Thanks. Fixed in v3.8.0.1.
