### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'PROCFS_PATH

### ISSUE THREAD

**Issue by yzho0907** [Lynten/stanford-corenlp#18]
Exception ignored in: <bound method StanfordCoreNLP.__del__ of <stanfordcorenlp.corenlp.StanfordCoreNLP object at 0x7f5d1e4856d8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/stanfordcorenlp/corenlp.py", line 111, in __del__
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 349, in __init__
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 370, in _init
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 849, in __init__
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 151, in get_procfs_path
AttributeError: 'NoneType' object has no attribute 'PROCFS_PATH
AttributeError: 'NoneType' object has no attribute 'PROCFS_PATH

**Comment by Vimos** [comment]
I am facing a similar problem, it does not always show up though.
```
Exception ignored in: <bound method StanfordCoreNLP.__del__ of <stanfordcorenlp.corenlp.StanfordCoreNLP object at 0x7f05e943ee80>>
Traceback (most recent call last):
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/stanfordcorenlp/corenlp.py", line 111, in __del__
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/psutil/__init__.py", line 401, in __init__
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/psutil/__init__.py", line 423, in _init
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/psutil/_pslinux.py", line 1396, in __init__
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/psutil/_pslinux.py", line 217, in get_procfs_path
KeyError: 'psutil'
```

**Comment by yzho0907** [comment]
it just like happens randomly but it is annoying anymore, hope it gets fixed!

**Comment by Lynten** [comment]
Fixed in new version. Thanks.
