### ISSUE TITLE
Corenlp server is not available

### ISSUE THREAD

**Issue by isofun** [Lynten/stanford-corenlp#87]
Traceback (most recent call last):
  File "test_ner2.py", line 3, in <module>
    nlp = StanfordCoreNLP(r'/Users/suyifan/stanford-corenlp-full-2018-10-05', lang='zh')
  File "//anaconda3/lib/python3.7/site-packages/stanfordcorenlp/corenlp.py", line 115, in __init__
    raise ValueError('Corenlp server is not available')
ValueError: Corenlp server is not available

Mac OS
python3.7

**Comment by tolerancecky** [comment]
I have the same problem. Have you got an solution to the probelm?

**Comment by yuran986** [comment]
I have the same problem, too. Did you guys solve it?
